version: '2'
services:
  web:
    command: /bin/bash -c "cd src && python manage.py collectstatic --noinput && /usr/local/bin/gunicorn sous-chef.wsgi:application -w 2 -b :8000"
    volumes:
      - /code/src/sous-chef/static
    expose:
      - "8000"
