version: '2'
services:
  db:
    restart: always
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: feast
    volumes:
      - ./tools/mariadb:/var/lib/mysql

  web:
    restart: always
    build: .
    depends_on:
      - db

  nginx:
    restart: always
    build: tools/nginx
    command: /bin/bash -c "nginx"
    ports:
      - "80:80"
    volumes:
      - /code/src/sous-chef/static:/usr/share/nginx/html
    volumes_from:
      - web
    depends_on:
      - web
